server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: user-management-service
          uri: lb://user-management-service
          predicates:
            - Path=/jum/**
        - id: ps-service
          uri: lb://ps-service
          filters: AuthHeaderFilter
          predicates:
            - Header=Authorization, Bearer (.*)
            - Path=/ps/**

