server:
  port: 8081

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka-service:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: ps-service
          uri: lb://ps-service
          predicates:
            - Path=/ps/**
        - id: jum-service
          uri: lb://jum-service
          predicates:
            - Path=/jum/**
        - id: jld-service
          uri: lb://jld-service
          predicates:
            - Path=/jld/**
      default-filters: TokenRelay
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/SSO
        registration:
          spring-cloud-gateway-client:
            client-id: mferrero
            client-secret: QoAoGXs5QKFUQZ3daIl9hNYZ0UxSQeG2
            provider: keycloak
            scope:
              - openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/login/oauth2/code/mferrero
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/SSO